[Macro1]
Nombre=Poción de Remover Parálisis (Alquimia)
Grh=891
Tipo=4
Slot=9
SlotSpell=0
ObjIndex=893

[Macro2]
Nombre=Arco Élfico
Grh=917
Tipo=4
Slot=15
SlotSpell=0
ObjIndex=899

[Macro3]
Nombre=Poción Roja
Grh=542
Tipo=4
Slot=18
SlotSpell=0
ObjIndex=38

[Macro4]
Nombre=Arco Élfico
Grh=917
Tipo=4
Slot=16
SlotSpell=0
ObjIndex=899

[Macro5]
Nombre=Poción Roja
Grh=542
Tipo=4
Slot=9
SlotSpell=0
ObjIndex=38

[Macro6]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro7]
Nombre=Flecha Explosiva
Grh=755
Tipo=3
Slot=22
SlotSpell=0
ObjIndex=1082

[Macro8]
Nombre=Flecha Paralizante
Grh=754
Tipo=3
Slot=11
SlotSpell=0
ObjIndex=1085

[Macro9]
Nombre=Flecha Incendiaria
Grh=753
Tipo=3
Slot=16
SlotSpell=0
ObjIndex=1084

[Macro10]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro11]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0
