[Macro1]
Nombre=MEDITAR
Grh=17506
Tipo=1
Slot=0
SlotSpell=0
ObjIndex=0

[Macro2]
Nombre=Proyectil Magico
Grh=609
Tipo=2
Slot=0
SlotSpell=1
ObjIndex=0

[Macro3]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro4]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro5]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro6]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro7]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro8]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro9]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro10]
Nombre=
Grh=0
Tipo=0
Slot=0
SlotSpell=0
ObjIndex=0

[Macro11]
Nombre=Poción Roja (Newbies)
Grh=542
Tipo=4
Slot=2
SlotSpell=0
ObjIndex=461
